from mido import Message, MidiFile, MidiTrack,MetaMessage
inp = MidiFile("notetest.mid")
print(inp)
mid = MidiFile(type=1)
track = MidiTrack()
settrack=MidiTrack()
settrack.append(MetaMessage('time_signature',numerator=4,denominator=4,clocks_per_click=24,notated_32nd_notes_per_beat=8,time=0))
settrack.append(MetaMessage('set_tempo',tempo=50000,time=0))
settrack.append(MetaMessage('end_of_track',time=0))
track.append(MetaMessage('track_name',name='SONG',time=0))
track.append(Message('program_change', program=0, time=0))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
track.append(Message('note_on', note=48, velocity=50, time=0))
track.append(Message('note_off', note=48, velocity=0, time=360))
mid.tracks.append(settrack)
mid.tracks.append(track)
mid.save('new_song.mid')